### ISSUE TITLE
[Gateway API] Cloud resources for Kubernetes Gateway API

### ISSUE THREAD

**Issue by nlamirault** [portefaix/portefaix-infrastructure#1310]
See: https://gateway-api.sigs.k8s.io/implementations/

```[tasklist]
### Tasks
- [ ] https://github.com/portefaix/portefaix-infrastructure/issues/1311
- [ ] https://github.com/portefaix/portefaix-infrastructure/issues/1312
- [ ] https://github.com/portefaix/portefaix-infrastructure/issues/1313
```
